#include <QMainWindow>
#include <QMessageBox>
#include <QFileDialog>
#include <QWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QList>
#include <QMap>
#include <QPushButton>
#include <QLineEdit>
#include <QLabel>
#include <QSpacerItem>
#include <QSizePolicy>
#include <QFuture>
#include <QFutureWatcher>
#include <QtConcurrent/QtConcurrentRun>
#include <QString>
#include <QIcon>
#include <QChar>
#include <QMovie>
#include <QFile>
#include <QDebug>
#include <QIntValidator>
#include <QKeyEvent>
#include <QMouseEvent>
#include <QMutex>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QIntValidator>
#include <QMainWindow>
#include <QMessageBox>
#include <QFileDialog>
#include <QDialog>
#include <QWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QList>
#include <QPushButton>
#include <QLineEdit>
#include <QLabel>
#include <QSpacerItem>
#include <QSizePolicy>
#include <QFuture>
#include <QFutureWatcher>
#include <QtConcurrent/QtConcurrentRun>
#include <QString>
#include <QIcon>
#include <QChar>
#include <QMovie>
#include <QFile>
#include <QDebug>
#include <QIntValidator>
#include <QKeyEvent>
#include <QMouseEvent>
#include <QMutex>
#include <QListWidget>
#include <QStackedWidget>
#include <QSettings>
#include <QObject>
#include <QLineEdit>
#include <QString>
#include <QList>
#include <QDebug>
#include <QMessageBox>
#include <QGridLayout>
#include <QLabel>
#include <QMouseEvent>
#include <QDrag>
#include <QApplication>
#include <QMimeData>
#include <QPixmap>
#include <QPoint>
#include <QVariant>
#include <QAction>
#include <QApplication>
#include <QButtonGroup>
#include <QHeaderView>
#include <QMainWindow>
#include <QMenuBar>
#include <QStatusBar>
#include <QToolBar>
#include <QWidget>
#include <QPushButton>
#include <QToolButton>
#include <QDrag>
#include <QMimeData>
#include <QByteArray>
#include <QDataStream>
#include <QPushButton>
#include <QLineEdit>
#include <QSpacerItem>
#include <QScrollArea>
#include <QDesktopWidget>
#include "QTime"
#include <QGroupBox>
